# Generated by Django 5.0.1 on 2024-02-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_options_rename_name_profile_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image_url',
        ),
    ]
